# -*- coding: utf-8 -*-
"""SimuladorTiemposColas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sP0orL3mAihpTp1cernRth8gADHexGhc
"""

# =========================================
# FORMULARIO DE LEADS (SQLite) + BUSCADOR
# =========================================
import os, time, sqlite3, pandas as pd, matplotlib.pyplot as plt
from ipywidgets import (
    Text, Textarea, Dropdown, Button, HBox, VBox, Layout, HTML, Output,
    GridspecLayout, DatePicker
)
from IPython.display import display, clear_output

# Descarga en Colab
try:
    from google.colab import files
    IN_COLAB = True
except Exception:
    IN_COLAB = False

DB_PATH, TABLE = "leads.db", "leads"

# ---------- DB helpers ----------
def init_db():
    con = sqlite3.connect(DB_PATH)
    cur = con.cursor()
    cur.execute(f"""
        CREATE TABLE IF NOT EXISTS {TABLE} (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            created_at TEXT NOT NULL,
            tema TEXT, nombre TEXT, apellido TEXT, puesto TEXT,
            tel_trabajo TEXT, tel_movil TEXT, email TEXT,
            compania TEXT, web TEXT,
            calle1 TEXT, calle2 TEXT, calle3 TEXT,
            ciudad TEXT, estado TEXT, pais TEXT,
            notas TEXT, fuente TEXT
        )
    """)
    con.commit(); con.close()

def insert_lead(row):
    con = sqlite3.connect(DB_PATH)
    cur = con.cursor()
    cols = ("created_at, tema, nombre, apellido, puesto, tel_trabajo, tel_movil, email, "
            "compania, web, calle1, calle2, calle3, ciudad, estado, pais, notas, fuente")
    vals = tuple(row[c] for c in [
        "created_at","tema","nombre","apellido","puesto","tel_trabajo","tel_movil","email",
        "compania","web","calle1","calle2","calle3","ciudad","estado","pais","notas","fuente"
    ])
    cur.execute(f"INSERT INTO {TABLE} ({cols}) VALUES ({','.join(['?']*18)})", vals)
    con.commit(); con.close()

def query_df(text="", fuente="(todas)", f_ini=None, f_fin=None):
    """
    Busca por texto (LIKE en varias columnas), fuente y rango de fechas [inicio, fin].
    f_ini / f_fin son objetos datetime.date (DatePicker) o None.
    """
    init_db()
    con = sqlite3.connect(DB_PATH)

    where = []
    params = []

    if text:
        like = f"%{text.strip()}%"
        # columnas a buscar
        cols = ["tema","nombre","apellido","email","compania","tel_trabajo","tel_movil","ciudad","estado","pais","notas","web"]
        where.append("(" + " OR ".join([f"{c} LIKE ?" for c in cols]) + ")")
        params += [like]*len(cols)

    if fuente and fuente != "(todas)":
        where.append("fuente = ?")
        params.append(fuente)

    if f_ini:
        where.append("created_at >= ?")
        params.append(f"{f_ini.strftime('%Y-%m-%d')} 00:00:00")
    if f_fin:
        where.append("created_at <= ?")
        params.append(f"{f_fin.strftime('%Y-%m-%d')} 23:59:59")

    sql = f"SELECT * FROM {TABLE}"
    if where:
        sql += " WHERE " + " AND ".join(where)
    sql += " ORDER BY id DESC"

    df = pd.read_sql_query(sql, con, params=params)
    con.close()
    return df

def export_db_to_csv(path="leads_export.csv", df=None):
    (df if df is not None else query_df()).to_csv(path, index=False)
    return path

# ---------- UI helpers ----------
def label(text):
    return HTML(f"<div style='font-family:Inter,system-ui;text-align:right;font-weight:600;padding:6px 10px 0 0;color:#111827;white-space:nowrap'>{text}</div>")
def fullw(): return Layout(width='100%')

# ---------- Widgets de captura ----------
tema       = Text(placeholder="Miranza - Interés en Fundanet", layout=fullw())
compania   = Text(placeholder="Miranza",                       layout=fullw())
nombre     = Text(placeholder="David",                         layout=fullw())
apellido   = Text(placeholder="Castro Miranza",                layout=fullw())
puesto     = Text(placeholder="---",                           layout=fullw())
tel_trab   = Text(placeholder="---",                           layout=fullw())
tel_movil  = Text(placeholder="691091509",                     layout=fullw())
email      = Text(placeholder="nombre@empresa.com",            layout=fullw())
web        = Text(placeholder="https://miranza.es/",           layout=fullw())
calle1, calle2, calle3 = Text(layout=fullw()), Text(layout=fullw()), Text(layout=fullw())
ciudad     = Text(placeholder="Madrid",                        layout=fullw())
estado     = Text(placeholder="Madrid",                        layout=fullw())
pais       = Text(placeholder="España",                        layout=fullw())
fuente     = Dropdown(options=["Web","Evento","Referido","Campaña","Llamada","Email","Otro"], value="Web", layout=fullw())
notas      = Textarea(placeholder="Detalles, próximos pasos…", layout=Layout(width='100%', height='80px'))

# Grid alineada 4 columnas (Etiqueta | Campo | Etiqueta | Campo)
grid = GridspecLayout(8, 4, grid_gap="12px", layout=Layout(width='100%'))
grid[0,0]=label("Tema:");                 grid[0,1]=tema
grid[0,2]=label("Compañía:");             grid[0,3]=compania
grid[1,0]=label("Nombre:");               grid[1,1]=nombre
grid[1,2]=label("Apellido:");             grid[1,3]=apellido
grid[2,0]=label("Puesto:");               grid[2,1]=puesto
grid[2,2]=label("Teléfono del trabajo:"); grid[2,3]=tel_trab
grid[3,0]=label("Teléfono móvil:");       grid[3,1]=tel_movil
grid[3,2]=label("Correo electrónico:");   grid[3,3]=email
grid[4,0]=label("Sitio web:");            grid[4,1]=web
grid[4,2]=label("Estado/Provincia:");     grid[4,3]=estado
grid[5,0]=label("Ciudad:");               grid[5,1]=ciudad
grid[5,2]=label("País:");                 grid[5,3]=pais
grid[6,0]=label("Calle 1:");              grid[6,1]=calle1
grid[6,2]=label("Calle 2:");              grid[6,3]=calle2
grid[7,0]=label("Calle 3:");              grid[7,1]=calle3
grid[7,2]=label("Fuente del lead:");      grid[7,3]=fuente
notas_row = HBox([label("Notas:"), notas], layout=Layout(width="100%"))
notas_row.children[0].layout = Layout(width="180px")

# ---------- Widgets de búsqueda ----------
search_text   = Text(placeholder="Nombre, empresa, email, tema…", layout=Layout(width='50%'))
search_fuente = Dropdown(options=["(todas)","Web","Evento","Referido","Campaña","Llamada","Email","Otro"], value="(todas)")
search_ini    = DatePicker(description="", disabled=False)
search_fin    = DatePicker(description="", disabled=False)

btn_search    = Button(description='Buscar', button_style='primary', layout=Layout(width='140px', height='34px'))
btn_reset     = Button(description='Limpiar filtros', layout=Layout(width='160px', height='34px'))

search_bar = VBox([
    HTML("<div style='font-family:Inter,system-ui;font-weight:700;margin:4px 0 8px'>🔎 Búsqueda</div>"),
    HBox([
        HTML("<div style='width:90px;padding-top:6px;font-family:Inter,system-ui;text-align:right;color:#111827'><b>Texto:</b></div>"), search_text,
        HTML("<div style='width:90px;padding-top:6px;font-family:Inter,system-ui;text-align:right;color:#111827'><b>Fuente:</b></div>"), search_fuente,
        HTML("<div style='width:100px;padding-top:6px;font-family:Inter,system-ui;text-align:right;color:#111827'><b>Desde:</b></div>"), search_ini,
        HTML("<div style='width:70px;padding-top:6px;font-family:Inter,system-ui;text-align:right;color:#111827'><b>Hasta:</b></div>"), search_fin,
        btn_search, btn_reset
    ], layout=Layout(gap="10px", align_items="center"))
], layout=Layout(border='1px solid #e5e7eb', border_radius='12px', padding='12px'))

# ---------- Botones y salidas ----------
btn_save   = Button(description='Guardar lead', button_style='success', layout=Layout(width='220px', height='38px'))
btn_export = Button(description='Exportar resultados a CSV', button_style='primary', layout=Layout(width='240px', height='38px'))
btn_clear  = Button(description='Limpiar campos', layout=Layout(width='180px', height='38px'))
botonera   = HBox([btn_save, btn_export, btn_clear], layout=Layout(justify_content="flex-start", gap="12px", width="100%", margin='8px 0'))

out_msg   = Output(layout=Layout(border='1px solid #e5e7eb', border_radius='12px', padding='12px', width='100%'))
out_tabla = Output(layout=Layout(border='1px solid #e5e7eb', border_radius='12px', padding='12px', width='100%'))
out_chart = Output(layout=Layout(border='1px solid #e5e7eb', border_radius='12px', padding='12px', width='100%'))
out_count = HTML("")

header = HTML("""
<div style="font-family:Inter,system-ui;background:linear-gradient(90deg,#16a34a,#065f46);
            color:white;border-radius:12px;padding:18px 28px;margin-bottom:14px;">
  <div style="font-size:24px;font-weight:700;">Registro de Leads de FUNDANET</div>
  <div style="font-size:14px;color:#d1fae5">Guardar • Buscar • Exportar</div>
</div>
""")

# ---------- Lógica de UI ----------
_last_results = None  # memoria de la última búsqueda para exportar

def render_table_and_chart(df):
    global _last_results
    _last_results = df.copy()
    with out_tabla:
        clear_output()
        if df.empty:
            out_count.value = "<div style='font-family:Inter,system-ui;color:#6b7280'>0 resultados</div>"
            display(HTML("<div style='font-family:Inter,system-ui;color:#6b7280'>No hay datos para mostrar.</div>"))
        else:
            out_count.value = f"<div style='font-family:Inter,system-ui'>Resultados: <b>{len(df)}</b></div>"
            vis = df.drop(columns=["id"]).rename(columns={
                "created_at":"Fecha/Hora","tema":"Tema","nombre":"Nombre","apellido":"Apellido",
                "puesto":"Puesto","tel_trabajo":"Teléfono del trabajo","tel_movil":"Teléfono móvil",
                "email":"Correo electrónico","compania":"Compañía","web":"Sitio web",
                "calle1":"Calle 1","calle2":"Calle 2","calle3":"Calle 3",
                "ciudad":"Ciudad","estado":"Estado/Provincia","pais":"País",
                "notas":"Notas","fuente":"Fuente del lead"
            })
            display(vis)

    with out_chart:
        clear_output()
        if _last_results is None or _last_results.empty:
            display(HTML("<div style='font-family:Inter,system-ui;color:#6b7280'>Añade leads o ajusta filtros para ver el gráfico.</div>"))
            return
        counts = _last_results["fuente"].value_counts().sort_index()
        plt.figure(figsize=(7.5,3))
        counts.plot(kind="bar")
        plt.title("Distribución de leads por fuente")
        plt.ylabel("Número de leads"); plt.xticks(rotation=0)
        plt.grid(True, axis='y', linestyle='--', alpha=0.35)
        plt.tight_layout(); plt.show()

def do_search(_=None):
    df = query_df(
        text=search_text.value,
        fuente=search_fuente.value,
        f_ini=search_ini.value,
        f_fin=search_fin.value
    )
    render_table_and_chart(df)

def guardar_lead(_):
    row = {
        "created_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        "tema": tema.value or "", "nombre": nombre.value or "", "apellido": apellido.value or "",
        "puesto": puesto.value or "", "tel_trabajo": tel_trab.value or "", "tel_movil": tel_movil.value or "",
        "email": email.value or "", "compania": compania.value or "", "web": web.value or "",
        "calle1": calle1.value or "", "calle2": calle2.value or "", "calle3": calle3.value or "",
        "ciudad": ciudad.value or "", "estado": estado.value or "", "pais": pais.value or "",
        "notas": notas.value or "", "fuente": fuente.value or ""
    }
    insert_lead(row)
    with out_msg:
        clear_output()
        display(HTML(f"""
        <div style="font-family:Inter,system-ui;background:#ecfdf5;color:#065f46;
                    border:1px solid #bbf7d0;border-radius:10px;padding:10px 12px;">
          ✅ <b>Lead guardado:</b> {row['nombre']} {row['apellido']} — {row['tema']}
        </div>"""))
    do_search()  # refresca con filtros activos

def export_results(_):
    path = export_db_to_csv(df=_last_results)
    if IN_COLAB and os.path.exists(path): files.download(path)
    with out_msg:
        clear_output()
        display(HTML(f"<div style='font-family:Inter,system-ui;background:#eff6ff;color:#1d4ed8;border:1px solid #bfdbfe;border-radius:10px;padding:10px 12px;'>💾 Exportado a <code>{path}</code>.</div>"))

def limpiar_campos(_):
    for wdg in [tema,nombre,apellido,puesto,tel_trab,tel_movil,email,compania,web,
                calle1,calle2,calle3,ciudad,estado,pais,notas]:
        wdg.value = ""
    fuente.value = "Web"

# Eventos
btn_save.on_click(guardar_lead)
btn_export.on_click(export_results)
btn_clear.on_click(limpiar_campos)
btn_search.on_click(do_search)
btn_reset.on_click(lambda _:(search_text.set_trait("value",""), search_fuente.set_trait("value","(todas)"),
                             search_ini.set_trait("value",None), search_fin.set_trait("value",None), do_search()))

# Render
init_db()
display(VBox([
    header,
    VBox([grid, HBox([label("Notas:"), notas], layout=Layout(width='100%'))],
         layout=Layout(border='1px solid #e5e7eb', border_radius='12px', padding='16px', width='98%')),
    HBox([btn_save, btn_export, btn_clear],
         layout=Layout(justify_content="flex-start", gap="12px", width="100%", margin='8px 0')),
    search_bar,
    out_msg,
    HBox([out_count], layout=Layout(margin="6px 0")),
    out_chart,
    out_tabla
]))

# Primera carga (sin filtros = todo)
do_search()